### Setup envirnonment 

In [1]:
%load_ext autoreload
%autoreload 2

### Import necessaary libraries

In [45]:
import tensorflow as tf
import tensorflow.contrib.slim as slim
import tensorflow.contrib.slim.nets as nets

import tempfile
from urllib.request import urlretrieve
import tarfile
import os

import json
import matplotlib.pyplot as plt

import PIL
import numpy as np

import imp

### Import my library

In [41]:
import patch_utils

### Classification cell

In [172]:
imp.reload(patch_utils)

# get random N to not to  confuse yourself
N = np.random.randint(1, 5)
Length = np.random.randint(50, 60)
Width = np.random.randint(50, 60)

print("N =", N)
print("Size =", Length, "x", Width)

# Allows not to reboot kernel on each initialization
tf.reset_default_graph()   

# =============================================================== #

# declare example of input to debug
ex_folded_patches = tf.get_variable(name="folded_patches", initializer=tf.zeros(shape=(N, Length, Width, 3)) )
#ex_x_shifts = tf.placeholder(name="x_shifts", shape =(N,), dtype=tf.int32 )
#ex_y_shifts = tf.placeholder(name="y_shifts", shape =(N,), dtype=tf.int32 )
ex_x_shift = tf.constant(1, name="x_shifts", shape =(), dtype=tf.int32 )
ex_y_shift = tf.constant(1, name="y_shifts", shape =(), dtype=tf.int32 )

ex_mapped_patches1 = patch_utils.shift(ex_folded_patches, ex_x_shift, ex_y_shift)

# print to the output
printer = tf.print(ex_mapped_patches1)

# =============================================================== #


# # declare example of input to debug
# ex_mapped_patches = tf.get_variable(name="mapped_patches", initializer=tf.zeros(shape=(N, 300, 300, 3)) )
# ex_original_images = tf.get_variable(name="original_images", initializer=tf.zeros(shape=(N, 300, 300, 3)) )


# # get input for the neuronet
# ex_images_with_patches = patch_utils.applicator(ex_mapped_patches, ex_original_images)

# # print to the output
# printer2 = tf.print(ex_images_with_patches)

# add an operation to initialize input
patches_initializer = tf.variables_initializer([])

N = 4
Size = 59 x 52


### Save current graph

In [175]:
# use this cell if you need to save graph to corresponding folder 
writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())

# Run learning 

### Classification run

In [174]:
a = np.ones((N, 300, 300, 3)) * (-2)
a[0][0][0][0:3] = 0.5
b = np.ones((N, 300, 300, 3)) * 5 


c = np.ones((N, Length, Width, 3))
d = np.zeros((N, ))
e = np.zeros((N, ))
f = np.ndarray(shape=(), dtype=np.int32)
f = 0
g = np.ndarray(shape=(), dtype=np.int32)
g = 0

my_feed_dict = {
#    ex_mapped_patches: a,
#    ex_original_images: b,
    ex_folded_patches: c,
#    ex_x_shifts: d,
#    ex_x_shifts: e
#    ex_x_shift: f,
#    ex_x_shift: g
}

with tf.Session() as sess:    
    # run the variable initializer operation
    sess.run(patches_initializer)    
    
    # now let's evaluate their value
    sess.run(printer, feed_dict=my_feed_dict)
    
    

[[[[-2 -2 -2]
   [-2 -2 -2]
   [-2 -2 -2]
   ...
   [-2 -2 -2]
   [-2 -2 -2]
   [-2 -2 -2]]

  [[-2 -2 -2]
   [1 1 1]
   [1 1 1]
   ...
   [-2 -2 -2]
   [-2 -2 -2]
   [-2 -2 -2]]

  [[-2 -2 -2]
   [1 1 1]
   [1 1 1]
   ...
   [-2 -2 -2]
   [-2 -2 -2]
   [-2 -2 -2]]

  ...

  [[-2 -2 -2]
   [-2 -2 -2]
   [-2 -2 -2]
   ...
   [-2 -2 -2]
   [-2 -2 -2]
   [-2 -2 -2]]

  [[-2 -2 -2]
   [-2 -2 -2]
   [-2 -2 -2]
   ...
   [-2 -2 -2]
   [-2 -2 -2]
   [-2 -2 -2]]

  [[-2 -2 -2]
   [-2 -2 -2]
   [-2 -2 -2]
   ...
   [-2 -2 -2]
   [-2 -2 -2]
   [-2 -2 -2]]]


 [[[-2 -2 -2]
   [-2 -2 -2]
   [-2 -2 -2]
   ...
   [-2 -2 -2]
   [-2 -2 -2]
   [-2 -2 -2]]

  [[-2 -2 -2]
   [1 1 1]
   [1 1 1]
   ...
   [-2 -2 -2]
   [-2 -2 -2]
   [-2 -2 -2]]

  [[-2 -2 -2]
   [1 1 1]
   [1 1 1]
   ...
   [-2 -2 -2]
   [-2 -2 -2]
   [-2 -2 -2]]

  ...

  [[-2 -2 -2]
   [-2 -2 -2]
   [-2 -2 -2]
   ...
   [-2 -2 -2]
   [-2 -2 -2]
   [-2 -2 -2]]

  [[-2 -2 -2]
   [-2 -2 -2]
   [-2 -2 -2]
   ...
   [-2 -2 -2]
   [-2 -2 -2]
 

In [ ]:
patch_utils.applicator()

# Analyze