# Wrinkles Generator 

In [ ]:
import cv2
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

original_image = cv2.imread("test.jpeg")
original_image=cv2.cvtColor(original_image,cv2.COLOR_BGR2RGB)
print(type(original_image))
print(original_image.shape)
print(original_image.size)
figure_size = 15
plt.figure(figsize=(figure_size,figure_size))
plt.imshow(original_image)
plt.show()

In [ ]:
!pip install --upgrade pip
!pip install scikit-image

In [ ]:
from skimage import io
import numpy as np
import matplotlib.pyplot as plt

original_image = cv2.imread("test.jpeg")
original_image=cv2.cvtColor(original_image,cv2.COLOR_BGR2RGB)

# Start coordinate, here (225, 0) 
# represents the top right corner of image 
start_point = (500, 0) 
  
# End coordinate, here (0, 225) 
# represents the bottom left corner of image 
end_point = (500, 1250) 
  
color = (192, 192, 192) 
  
thickness = 50
  
# Using cv2.line() method 
# Draw a diagonal black line with thickness of 5 px 
line_image = cv2.line(original_image, start_point, end_point, color, thickness) 

figure_size = 15
plt.figure(figsize=(figure_size,figure_size))
plt.imshow(line_image)
line_image = line_image.reshape((original_image.shape))
print("Line Image Shape: {}".format(line_image.shape))
print("Line Image Size: {}".format(line_image.size))
print("Total Pixels Removed: {}".format(thickness*
                                        ((start_point[0]-end_point[0])**2+(start_point[1]-end_point[1])**2)**(1/2)))

In [ ]:
search_line = line_image[500]
v = 192  # target value
e = 3  # allowed epsilon
include = []
start = 0
for i, px in enumerate(search_line):
    is_gray = np.all((px[:3] > (v-e)) & (px[:3] < (v+e)))
    if is_gray and start is not None:
        include.append((start, i))
        start = None
    elif not is_gray and start is None:
        start = i
print(include)
if start is not None:
    include.append((start, len(search_line)))
print(include)
slices = [line_image[:, start:end] for start, end in include]
foldedImage = np.concatenate(slices,1)

# Add [0, 0, 0] fill to the folded image
if (foldedImage.shape[0] != line_image.shape[0]):
    length_diff = line_image.shape[0]-foldedImage.shape[0]
    white_fill_length = np.zeros((foldedImage.shape[1], 3))
    for x in range(length_diff):
        foldedImage = np.append(foldedImage, white_fill_length)
        
print("Folded Image Shape: {}".format(foldedImage.shape))
print("Folded Image Type: {}".format(type(foldedImage)))

if (foldedImage.shape[1] != line_image.shape[1]):
    width_diff = line_image.shape[1]-foldedImage.shape[1]
    print("Width Difference: {}".format(width_diff))
    # white_fill_width = np.zeros((foldedImage.shape[0], width_diff, 3))
    white_fill_width = np.array([[[-2 for i in range(3)] for j in range(width_diff)] 
                                 for k in range(foldedImage.shape[0])])
    print("Shape of White Fill: {}".format(white_fill_width.shape))
    finalfoldedImage = np.append(foldedImage, white_fill_width, axis=1)

print(finalfoldedImage[0][948])
figure_size = 15
plt.figure(figsize=(figure_size,figure_size))
plt.imshow(finalfoldedImage.astype('uint8'))
print('Size of New Image: {}'.format(finalfoldedImage.shape))
plt.show()

In [ ]:
from skimage import io
import numpy as np
import matplotlib.pyplot as plt

original_image = cv2.imread("test.jpeg")
original_image=cv2.cvtColor(original_image,cv2.COLOR_BGR2RGB)

# Start coordinate, here (225, 0) 
# represents the top right corner of image 
start_point = (0, 500) 
  
# End coordinate, here (0, 225) 
# represents the bottom left corner of image 
end_point = (1000, 500) 
  
color = (192, 192, 192) 
  
thickness = 50
  
# Using cv2.line() method 
# Draw a diagonal black line with thickness of 5 px 
line_image = cv2.line(original_image, start_point, end_point, color, thickness)

figure_size = 15
plt.figure(figsize=(figure_size,figure_size))
plt.imshow(line_image)
line_image = line_image.reshape((original_image.shape))
print("Line Image Shape: {}".format(line_image.shape))
print("Line Image Size: {}".format(line_image.size))
print("Total Pixels Removed: {}".format(thickness*
                                        ((start_point[0]-end_point[0])**2+(start_point[1]-
                                                                           end_point[1])**2)**(1/2)))

In [ ]:
# We are searching through a single line of the length 
img_rotate_90_clockwise = cv2.rotate(line_image, cv2.ROTATE_90_CLOCKWISE)
#figure_size = 15
#plt.figure(figsize=(figure_size,figure_size))
#plt.imshow(img_rotate_90_clockwise.astype('uint8'))
#print('Size of New Image: {}'.format(img_rotate_90_clockwise.shape))
#plt.show()

search_line = img_rotate_90_clockwise[500]
v = 192  # target value
e = 3  # allowed epsilon
include = []
start = 0
for i, px in enumerate(search_line):
    is_gray = np.all((px[:3] > (v-e)) & (px[:3] < (v+e)))
    if is_gray and start is not None:
        include.append((start, i))
        start = None
    elif not is_gray and start is None:
        start = i
print(include)
if start is not None:
    include.append((start, len(search_line)))
print(include)
slices = [img_rotate_90_clockwise[:, start:end] for start, end in include]
foldedImage = np.concatenate(slices,1)
      
print("Folded Image Shape: {}".format(foldedImage.shape))
print("Folded Image Type: {}".format(type(foldedImage)))

if (foldedImage.shape[1] != line_image.shape[0]):
    width_diff = line_image.shape[0]-foldedImage.shape[1]
    print("Width Difference: {}".format(width_diff))
    white_fill_width = np.array([[[-2 for i in range(3)] for j in range(width_diff)] 
                                 for k in range(foldedImage.shape[0])])
    print("Shape of White Fill: {}".format(white_fill_width.shape))
    finalfoldedImage = np.append(foldedImage, white_fill_width, axis=1)

# Now rotate the image back 
finalfoldedImage = cv2.rotate(finalfoldedImage, cv2.ROTATE_90_COUNTERCLOCKWISE)
figure_size = 15
plt.figure(figsize=(figure_size,figure_size))
plt.imshow(finalfoldedImage.astype('uint8'))
print('Size of New Image: {}'.format(finalfoldedImage.shape))
plt.show()

In [ ]:
from skimage import io
import numpy as np
import matplotlib.pyplot as plt

original_image = cv2.imread("test.jpeg")
original_image=cv2.cvtColor(original_image,cv2.COLOR_BGR2RGB)

# Start coordinate, here (225, 0) 
# represents the top right corner of image 
start_point = (0, 0) 
  
# End coordinate, here (0, 225) 
# represents the bottom left corner of image 
end_point = (1000, 1250) 
  
color = (192, 192, 192) 
  
thickness = 50
  
# Using cv2.line() method 
# Draw a diagonal black line with thickness of 5 px 
line_image = cv2.line(original_image, start_point, end_point, color, thickness) 

figure_size = 15
plt.figure(figsize=(figure_size,figure_size))
plt.imshow(line_image)
line_image = line_image.reshape((original_image.shape))
print("Line Image Shape: {}".format(line_image.shape))
print("Line Image Size: {}".format(line_image.size))
print("Total Pixels Removed: {}".format(thickness*
                                        ((start_point[0]-end_point[0])**2+(start_point[1]-end_point[1])**2)**(1/2)))

In [ ]:
search_line = line_image[500]
v = 192  # target value
e = 3  # allowed epsilon
include = []
start = 0
for i, px in enumerate(search_line):
    is_gray = np.all((px[:3] > (v-e)) & (px[:3] < (v+e)))
    if is_gray and start is not None:
        include.append((start, i))
        start = None
    elif not is_gray and start is None:
        start = i
print(include)
if start is not None:
    include.append((start, len(search_line)))
print(include)
slices = [line_image[:, start:end] for start, end in include]
foldedImage = np.concatenate(slices,1)

# Add [0, 0, 0] fill to the folded image
if (foldedImage.shape[0] != line_image.shape[0]):
    length_diff = line_image.shape[0]-foldedImage.shape[0]
    white_fill_length = np.zeros((foldedImage.shape[1], 3))
    for x in range(length_diff):
        foldedImage = np.append(foldedImage, white_fill_length)
        
print("Folded Image Shape: {}".format(foldedImage.shape))
print("Folded Image Type: {}".format(type(foldedImage)))

if (foldedImage.shape[1] != line_image.shape[1]):
    width_diff = line_image.shape[1]-foldedImage.shape[1]
    print("Width Difference: {}".format(width_diff))
    white_fill_width = np.zeros((foldedImage.shape[0], width_diff, 3))
    print("Shape of White Fill: {}".format(white_fill_width.shape))
    finalfoldedImage = np.append(foldedImage, white_fill_width, axis=1)

print(finalfoldedImage[0][948])
figure_size = 15
plt.figure(figsize=(figure_size,figure_size))
plt.imshow(finalfoldedImage.astype('uint8'))
print('Size of New Image: {}'.format(finalfoldedImage.shape))
plt.show()

# TensorFlow Conversion

In [2]:
import tensorflow as tf
import math
import numpy as np

# image = np.array([[[1 for k in range(3)] for j in range(50)] for i in range(50)])
# print("The shape of the image is: {}".format(image.shape))
# ---------------------------------------- Points of Fold--------------------------------------------------------
# Vertical fold
# (25,0) -> (25,50)

# Resets variables
tf.reset_default_graph() 

# checkTest = tf.get_variable(initializer=input_start_pt[0], name='checkTest', dtype='int32')

# The shape parameter might throw an error due to list shape vs tuple in input_start_pt and input_end_pt
image = tf.placeholder(tf.int64, name='image', shape=(50, 50, 3))

starting_x = tf.placeholder(tf.int64, name='start_x')
starting_y = tf.placeholder(tf.int64, name='start_y')

end_x = tf.placeholder(tf.int64, name='end_x')
end_y = tf.placeholder(tf.int64, name='end_y')

thickness = tf.placeholder(tf.int64, name='thickness')
new_thickness = tf.divide(thickness,2)

# Find the change in fold to determine vertical or horizontal

def fn1(a, b):
    return tf.subtract(b, a)

vertical = tf.placeholder(tf.bool)
change = tf.cond(vertical, lambda: fn1(starting_y, end_y), lambda: fn1(starting_x, end_x))

# The starting and end points
starting_pt = tf.cond(vertical, lambda: starting_x, lambda: starting_y)

# Depending on the start/end points, we will flip the array to work with horizontal folds 
corrected_image = tf.cond(vertical, lambda: image, lambda: tf.image.rot90(image, k=1), name='corrected_image')

# Remove pixels from the start point to the end point
flattened_image = tf.reshape(corrected_image, [2500, 3])

# modulus_check = tf.mod(5, 3)

# created an empty image to add 
# folded_image = tf.Variable(np.empty((2500, 3), dtype=np.float32))

i = tf.constant(0, dtype='int64', name='i')
past_point_new = tf.constant(0, dtype='int64', name='past_point')
folded_image_new = tf.Variable(np.array([[0, 0, 0]], dtype=np.int64), name='folded_image')
test_run = tf.Variable(np.array([0], dtype=np.int64), name='test_run')

# the while condition
while_condition = lambda i, past_point, folded_image, test_run: tf.less(i, 2500)
def body(i, past_point, folded_image, test_run):
    # interval check sees if it is the starting point of each row using modulus
    # interval check will return true if the mod is equivalent to 0 
    interval_check = tf.cond(tf.reduce_all(tf.equal(tf.mod(i, starting_pt), 0)), lambda: tf.constant(True), 
                             lambda: tf.constant(False))
    interval_check = tf.cond(tf.equal(tf.mod(i, 50), 0), lambda: tf.constant(False), lambda: interval_check)
    
    # This is a test variable
    test_run = tf.cond(interval_check, lambda: tf.concat((test_run, [past_point]), axis=0), 
                       lambda: test_run)
    
    # This will fold the image at a location depending on the condition of interval_check
    folded_image = tf.cond(interval_check, 
                       lambda: tf.concat((folded_image, flattened_image[past_point:i]), axis=0), 
                       lambda: folded_image)
    
    past_point_loop = tf.cond(interval_check, lambda: tf.add(i, thickness), lambda: past_point)
    
    folded_image = tf.cond(tf.equal(i+1, 2500), 
                          lambda: tf.concat((folded_image, flattened_image[past_point:i+1]), axis=0),
                          lambda: folded_image)
    
    return [tf.add(i, 1), past_point_loop, folded_image, test_run]

# do the loop:
final = tf.while_loop(while_condition, body, 
         loop_vars=[i, past_point_new, folded_image_new, test_run],
         shape_invariants=[i.get_shape(), tf.TensorShape(None), tf.TensorShape(None), tf.TensorShape(None)])

# Now we have to add -2's to the end of each 
removed_image = final[2][1:]
removed_image_shape = tf.subtract(tf.constant(2500, dtype='int64'), 
                                  tf.multiply(tf.constant(50, dtype='int64'), thickness),
                                  name='removed_image_shape')


# --------------------------------------Time to Add -2 Fills------------------------------------------------
i = tf.constant(0, dtype='int64', name='i')
negative_two_fill = tf.Variable(np.array([[-2, -2, -2]], dtype=np.int64), name='negative_two_fill')


# --------------------------------------Loop to Generate the Appropriate Fill-------------------------------
fill_i = tf.constant(1, dtype='int64', name='fill_i')
negative_two_fill_add = negative_two_fill
while_condition_fill = lambda fill_i, negative_two_fill: tf.less(fill_i, thickness)

def fillLoop(fill_i, negative_two_fill):
    return [tf.add(fill_i,1), tf.concat((negative_two_fill, negative_two_fill_add), axis=0)]

fill_completed = tf.while_loop(while_condition_fill, fillLoop,
                              loop_vars=[fill_i, negative_two_fill],
                              shape_invariants=[i.get_shape(), tf.TensorShape(None)])
negative_two_fill = fill_completed[1]

# ---------------------------------------Remaining Variables------------------------------------------------
final_image = tf.Variable(np.array([[0, 0, 0]], dtype=np.int64), name='final_image')
test_final = tf.Variable(np.array([0], dtype=np.int64), name='test_final')
count = tf.constant(1, dtype='int64', name='count')
past_point_final = tf.constant(0, dtype='int64', name='past_point_final')


# --------------------------------------Beginning of While Loop----------------------------------------------
while_condition_final = lambda i, count, final_image, test_final, past_point_final: tf.less(i, 
                                                                                            removed_image_shape)
def finalLoop(i, count, final_image, test_final, past_point_final):
    # Whenever we encounter 50-thickness, we can add -2's to the array
    check = tf.add(i, tf.multiply(count, thickness))
    interval_check = tf.cond(tf.equal(tf.mod(check, 50), 0), 
                            lambda: tf.constant(True),
                            lambda: tf.constant(False))
    interval_check = tf.cond(tf.equal(i,0), lambda: tf.constant(False), lambda: interval_check)
    test_final = tf.cond(interval_check, lambda: tf.concat((test_final, [past_point_final]), axis=0), 
                       lambda: test_final)
    
    # Now we add to the final_image array every interval_check
    final_image = tf.cond(interval_check,
                        lambda: tf.concat((final_image, removed_image[past_point_final:i], 
                                          negative_two_fill), axis=0), 
                       lambda: final_image)
    past_point_final = tf.cond(interval_check, lambda: i, lambda: past_point_final)
    
    final_image = tf.cond(tf.equal(i+1, removed_image_shape), 
                          lambda: tf.concat((final_image, removed_image[past_point_final:i+1], 
                                          negative_two_fill), axis=0), 
                       lambda: final_image)
    
    return [tf.add(i, 1), tf.cond(interval_check, lambda: tf.add(count,1),
                                 lambda: count), final_image, test_final, past_point_final]
    
completed = tf.while_loop(while_condition_final, finalLoop, 
         loop_vars=[i, count, final_image, test_final, past_point_final],
         shape_invariants=[i.get_shape(), tf.TensorShape(None), tf.TensorShape(None), 
                           tf.TensorShape(None), tf.TensorShape(None)])

final_output = completed[2]

flattened_image = tf.reshape(corrected_image, [2500, 3])

init_op = tf.initialize_all_variables()

ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'init' type=NoOp>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/Users/MichaelK./.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 3346, in run_code
    return outflag  File "<ipython-input-1-ccd62aaab358>", line 151, in <module>
    init_op = tf.initialize_all_variables()  File "/Users/MichaelK./Desktop/SecurityProject/vEnv/lib/python3.5/site-packages/tensorflow_core/python/util/tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))


In [3]:
image_input = np.array([[[1 for k in range(3)] for j in range(50)] for i in range(50)])
print(image_input.shape)

with tf.compat.v1.Session() as sess:
    init_op.run()
    out = sess.run(removed_image, feed_dict={starting_x: 25, starting_y: 0, end_x: 25, 
                               end_y: 50, vertical: True,
                               image: image_input, thickness:5})
print(out)
print(out.shape)

(50, 50, 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]
 ...
 [1 1 1]
 [1 1 1]
 [1 1 1]]
(2250, 3)


In [6]:
image_input = np.array([[[1 for k in range(3)] for j in range(50)] for i in range(50)])
print(image_input.shape)

with tf.compat.v1.Session() as sess:
    init_op.run()
    out = sess.run(completed, feed_dict={starting_x: 25, starting_y: 0, end_x: 25, 
                               end_y: 50, vertical: True,
                               image: image_input, thickness:5})
print(out[2].shape)

(50, 50, 3)
(2501, 3)


In [ ]:
b